name: swapjobapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  http: ^0.13.3
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  url_launcher: ^6.1.0
  flutter_tags: ^0.4.9+1
  flutter_tindercard: ^0.2.0
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.4.0+1
  cupertino_icons: ^1.0.4
  google_sign_in: ^5.3.1
  local_auth: ^2.1.0
  geocode: 1.0.1
  flutter_speed_dial: ^6.0.0
  file_picker: ^4.6.1
  path: ^1.8.2
  dio: ^4.0.6
  ftpconnect: ^1.0.1
  flutter:
    sdk: flutter


dev_dependencies:

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/Icon/icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/